version: '3'

services:
  app:
    build: .
    command: ./scripts/run.sh
    environment:
      - DIJKSTRA_URL=${DIJKSTRA_URL}
      - NAMI_URL=${NAMI_URL}
      - GCP_API_KEY=${GCP_API_KEY}
    volumes:
      - .:/go/src/github.com/cfx-cv/suez:z
    ports:
      - "3001:8000"
