version: '3.5'

services:
  app:
    build: .
    command: ./scripts/run.sh
    environment:
      - DIJKSTRA_URL=${DIJKSTRA_URL}
      - NAMI_URL=${NAMI_URL}
      - GCP_API_KEY=${GCP_API_KEY}
    volumes:
      - .:/go/src/github.com/cfx-cv/suez:z
    expose:
      - "80"
    ports:
      - "81:80"
    networks:
      default:
        aliases:
          - suez_app

networks:
  default:
    name: gofeed-network
