version: '3.5'

services:
  app:
    build: .
    command: ./scripts/run.sh
    environment:
      - DIJKSTRA_URI=${DIJKSTRA_URI}
      - NAMI_URI=${NAMI_URI}
      - HERALD_URI=${HERALD_URI}
      - GCP_API_KEY=${GCP_API_KEY}
    volumes:
      - .:/go/src/github.com/cfx-cv/suez:z
    expose:
      - "80"
    networks:
      gofeed:
        aliases:
          - suez_app

networks:
  gofeed:
    name: gofeed
